### ISSUE TITLE
Yum require : question

### ISSUE THREAD

**Issue by Karen09** [thbe/puppet-rkhunter#7]
Hi Thomas

https://github.com/thbe/puppet-rkhunter/blob/master/manifests/init.pp#L70
can you explain where we need yum module ?and make for me proper can we run rkhunter module without thbe/yum module ? because i cant find where we need yum.(also not documented ?)

Regards 
Karen

**Comment by thbe** [comment]
Hi Karen,

the rkhunter package is not in the standard RHEL/SL/CentOS repository, it
is part of EPEL. So you need to activate EPEL to use rkhunter. The yum
module activates per default EPEL, so that's the reason why it's in the
dependencies (otherwise testing the module with vagrant minimal OS won't
work). With other words, if you have EPEL already activated, the yum module
is not necessary.

Regards Thomas

2015-03-20 10:34 GMT+01:00 Karen <notifications@github.com>:

> Hi Thomas
>
> https://github.com/thbe/puppet-rkhunter/blob/master/manifests/init.pp#L70
> can you explain where we need yum module ?and make for me proper can we
> run rkhunter module without thbe/yum module ? because i cant find where we
> need yum.(also not documented ?)
>
> Regards
> Karen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thbe/puppet-rkhunter/issues/7>.
>



-- 
Linux ... enjoy the ride!

**Comment by Karen09** [comment]
Hi Thomas 

Thanks for info .

Regards 
Karen
